// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using calendify.Data;

#nullable disable

namespace calendify_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241001100649_seeding_db_events_table")]
    partial class seeding_db_events_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("calendify_app.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("calendify_app.Models.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("calendify_app.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminApproval")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99f2cebf-e1d1-4a84-9331-78e6812dd580"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 1, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "baba",
                            EndTime = new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Rotterdam",
                            StartTime = new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Dinner op kantoor"
                        },
                        new
                        {
                            Id = new Guid("8929c16d-cb08-4a4c-a06e-7379291ad951"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Een interactieve sessie over het verbeteren van productiviteit op de werkvloer.",
                            EndTime = new DateTime(2024, 10, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Amsterdam",
                            StartTime = new DateTime(2024, 10, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Workshop Productiviteit"
                        },
                        new
                        {
                            Id = new Guid("06a757aa-2e73-4a31-9ec4-b3e27e7412c7"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Een dag vol activiteiten om de samenwerking tussen teams te verbeteren.",
                            EndTime = new DateTime(2024, 10, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Den Haag",
                            StartTime = new DateTime(2024, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Teambuilding Dag"
                        },
                        new
                        {
                            Id = new Guid("591d5969-6a62-425a-add8-b95b6c13beec"),
                            AdminApproval = false,
                            Date = new DateTime(2024, 10, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Een creatieve sessie om nieuwe ideeën en innovaties te bedenken voor het bedrijf.",
                            EndTime = new DateTime(2024, 10, 12, 13, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Rotterdam",
                            StartTime = new DateTime(2024, 10, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Brainstorm Sessie"
                        },
                        new
                        {
                            Id = new Guid("b6cf6bba-c7b8-46f7-a911-389d4ac97cb5"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Een informele lunch waarbij een spreker zijn expertise deelt over een vakgebied.",
                            EndTime = new DateTime(2024, 10, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Utrecht",
                            StartTime = new DateTime(2024, 10, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lunch & Learn"
                        },
                        new
                        {
                            Id = new Guid("58be84cc-651e-4ca3-b43d-319e295f3055"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Presentatie van het nieuwe project voor een belangrijke klant.",
                            EndTime = new DateTime(2024, 10, 20, 15, 30, 0, 0, DateTimeKind.Utc),
                            Location = "Eindhoven",
                            StartTime = new DateTime(2024, 10, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Presentatie Klantproject"
                        },
                        new
                        {
                            Id = new Guid("8218f536-8436-4d3a-a4b9-da19cd0f6398"),
                            AdminApproval = true,
                            Date = new DateTime(2024, 10, 25, 16, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Vrijdagmiddagborrel om de werkweek af te sluiten met collega's.",
                            EndTime = new DateTime(2024, 10, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            Location = "Rotterdam",
                            StartTime = new DateTime(2024, 10, 25, 16, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Vrijmibo op kantoor"
                        });
                });

            modelBuilder.Entity("calendify_app.Models.EventAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Feedback")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Event_Attendance");
                });

            modelBuilder.Entity("calendify_app.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecurringDays")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("calendify_app.Models.Attendance", b =>
                {
                    b.HasOne("calendify_app.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("calendify_app.Models.Event", b =>
                {
                    b.HasOne("calendify_app.Models.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("calendify_app.Models.EventAttendance", b =>
                {
                    b.HasOne("calendify_app.Models.Event", "Event")
                        .WithMany("EventAttendance")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("calendify_app.Models.User", "User")
                        .WithMany("EventAttendance")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("calendify_app.Models.Event", b =>
                {
                    b.Navigation("EventAttendance");
                });

            modelBuilder.Entity("calendify_app.Models.User", b =>
                {
                    b.Navigation("EventAttendance");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
